### ISSUE TITLE
Error in assignID/ kovarex

### ISSUE THREAD

**Issue by ghost** [LovelySanta/FactorioMods#5] opened 2018-05-28 11:49 UTC
http://prntscr.com/jnkhql
Im not 100% sure whats causing your mod to conflict with other mods but if I had to guess, it has to do with Sigma Ones Nuclear mod: https://mods.factorio.com/mod/SigmaOne_Nuclear  
PS- Love your mods!

**Comment by LovelySanta** [comment] 2018-05-28 12:27
Hi,

First of all, thanks for the feedback, hope you'll get some nice play hours (weeks? months?) out of my mods.

On this note.. The issue is that SigmaOne_Nuclear removes the kovarex enrichment process technology research (this is against the philosophy of making mods compatible with other mods, do NOT remove vanilla stuff... [See this report too](https://mods.factorio.com/mod/SigmaOne_Nuclear/discussion/5af97afa38dff1000a3829bb]

This is nothing on my end. The only thing I can do is help [sigma1](https://mods.factorio.com/user/Sigma1) solve this issue... I've [messaged him on his mod page](https://mods.factorio.com/mod/SigmaOne_Nuclear/discussion/5b0bf651a968c7000a3588c9).

I see this as resolved since there is nothing I can do about this...

Greetings,
lovely_santa



PS: A quick fix for this:
In my mod, on [prototypes/technology/rocket-science.lua:72](https://github.com/LovelySanta/FactorioMods/blob/master/MoreScience/prototypes/technology/rocket-science.lua#L72) You can remove the Kovarex enrichment requirement. The line should look then like:

addRocketScienceTechnology("fusion-reactor", {"rocket", "fusion-reactor-equipment"})

**Closed as completed by LovelySanta** 2018-05-28 12:27 UTC
Labels: Compatibility Issue

**Comment by ghost** [comment] 2018-05-28 12:59
lovely_santa,
Thanks for the fast response, I wasn't sure who to contact ( not a programmer and I also use 160+ mods at any given time ) but was thinking this was going to be the case with this. Thanks for contacting him already and informing him, as well as providing a work-around! Keep up the great work sir, have a good memorial day (if you celebrate that).
-Splicer
